name: Integ test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: |
        sudo apt-get install -y build-essential cmake libboost-all-dev libcrypto++-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j 4
        cd ..
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      run: tox
